version: "3.9"
services:
  api:
    build: ./server
    command: ["python3", "-m", "flask", "run"]
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - ENV=production
  webserver:
    build: ./webserver
    command: ["node", "index.js"]
    container_name: webserver
    ports:
      - "8080:8080"
  client:
    build: ./client
    command: ["serve", "public"]
    ports:
      - "3000:3000"