version: "3.9"
services:
  api:
    build: ./server
    command: ["python3", "-m", "gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
    ports:
      - 5000
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - ENV=production
  nginx:
    build: ./nginx
    ports:
      - 5000:1337
    depends_on:
      - api
  webserver:
    build: ./webserver
    command: ["node", "index.js"]
    ports:
      - 8080:8080
  client:
    build: 
      context: ./client
      args:
        - ARG_ENV=production
    command: ["serve", "public"]
    ports:
      - 3000:3000
    depends_on:
      - webserver
      - nginx